### ISSUE TITLE
Controller memory issue

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#157]
**Description**

After several reconciliations (for me ~3) that trigger a call to istio Install, the controller terminates because it hits the memory limit. It looks like there is a memory leak that causes the memory usage to increase with each reconciliation.

**Expected result**

Reconciliations can be executed without controller being OOM killed.

**Actual result**
Controller is OOM killed.

**Steps to reproduce**
- Deploy the controller
- Apply Istio CR
- Update Istio CR multiple times to trigger a call to Istio Installation

**Troubleshooting**

**Comment by barchw** [comment]
Looks like the memory usage is increasing whenever I install/uninstall Istio (every increase was caused by deletion of Istio CR and reapply). Memory is not being released afterwards.
![Screenshot 2023-06-06 at 12 26 20](https://github.com/kyma-project/istio/assets/103247439/d4f1b70d-3eed-4fcd-af12-4ffc7c0040d2)

**Comment by kolodziejczak** [comment]
I found that errors are thrown while applying Istio CR 2nd time and above.
It looks like it's timing is corelated with memory increase.
![image](https://github.com/kyma-project/istio/assets/69915024/12311626-24ca-4c4e-87de-7d689cdd7b4b)

I have 2 suspicions about why it can be caused.
1st - stale cache
2nd - working with new CR objects instead of reference and passing those new ones to update [not too much verified yet]

**Comment by kolodziejczak** [comment]
Heap profiling between changes to Istio CR
![heap001](https://github.com/kyma-project/istio/assets/69915024/3194b8a3-2aca-43fc-81c3-b267681a75fd)
![heap002](https://github.com/kyma-project/istio/assets/69915024/79fe1e04-ec02-4ce0-9031-f536b834bed5)
![heap003](https://github.com/kyma-project/istio/assets/69915024/5392ffed-a013-4cbd-9352-54ee192cb0fc)
![heap004](https://github.com/kyma-project/istio/assets/69915024/14bf3d66-7b1f-47c1-aca4-844c4a5c69f6)

**Comment by kolodziejczak** [comment]
EDIT: It seems that this memory leak is not related to the error of modifying stale CR, because after disabling cache the error disappears but the memory usage is still not working correctly

**Comment by kolodziejczak** [comment]
EDIT: 
- Memory leak entry point is Istio's kube package - ApplyYAMLFile function.
- It's part of webhook generation and we cannot disable it
- The problem doesn't occur on master branch because of transition to server side apply

**Comment by triffer** [comment]
When doing the reconciliation of the Istio webhooks during call of install, there is a memory leak in Istio code. This memory leak happens when the webhook manifests are applied using the [ApplyYAMLFiles function](https://github.com/istio/istio/blob/6f0d7ae668c847f378107d409415e0dd34278480/istioctl/pkg/tag/generate.go#L330).
This function orchestrates requests to the cluster using kubectl commands.
In Istio master branch the implementation for webhook reconciliation was changed to use server-side apply, instead of Istio implemented CLIClient. There were also PRs to 1.16 and 1.17 that were merged, but reverted again. The PR to 1.18 was not merged, but closed because of an issue that was later fixed on master branch.

We were evaluating different options and it looks like the only option left is:
Execute the Install in a sub process, so the memory will be freed after install execution. This can be done by including istioctl in the Docker image or build a binary with our invocation of the istio.Install.
