### ISSUE TITLE
Library managing sidecars

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#26]
**Description**

Library should implement:
- analysing of workloads that should be part of service mesh and adding it if needed
- keeping version of sidecars up to date

ACs:
- [ ] workloads should be part of service mesh if configured
- [ ] sidecar version is up to date
- [ ] workloads are NOT labeled / annotated
- [ ] no dependency to reconciler

**Reasons**

modularization

**DoD:**
- [ ] provide unit tests

**[WIP] PR**
-  https://github.com/kyma-project/istio/pull/37

**Comment by werdes72** [comment]
TODO:

- [ ] Since we don't want to label/annotate customer workloads anymore, decide what to do with existing annotations (ignore?)
- [ ] Finish pod getting logic (getting sidecar names from annotations, get image prefix and suffix from config, sidecar injection logic, cni configuration)
- [ ] Get parent objects which needs to be rolled out
- [ ] Delete pod/perform rollout

**Comment by triffer** [comment]
To be discussed:
To force a rollout of pods we need to change anything in the template of the pod. In the existing implementation the annotation `kubectl.kubernetes.io/restartedAt` was added. We an AC to not annotate the workloads. How should we deal with this?
